name: Video Idea
description: New idea for a YouTube video
title: "What's the title?"
labels: ["Idea"]
projects: ["tommerty/10"]
assignees:
  - tommerty
body:
- type: input
  id: title
  attributes:
    label: General idea
    description: "A basic idea for a title"
    placeholder: "..."
  validations:
    required: true
- type: textarea
  id: idea
  attributes:
    label: Further explanation
    description: "What's the main concept, and how should it be structured?"
  validations:
    required: true
- type: input
  id: repo
  attributes:
    label: Associated repository or links
    description: "Does this video have any code references or need a link to anything specific?"
    placeholder: "https://github.com/tommerty/..."
    value: "https://github.com/tommerty/..."
